### ISSUE TITLE
ValidateError

### ISSUE THREAD

**Issue by noamix** [ingadhoc/odoo-argentina#11]
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/addons/account/account.py", line 800, in write
    return super(account_journal, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 363, in old_api
result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3726, in write
    self._write(old_vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3897, in _write
    recs._validate_fields(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 1276, in _validate_fields
    raise ValidationError("Error while validating constraint\n\n%s" % tools.ustr(e))
ValidationError: ('ValidateError', u'Error while validating constraint\n\nValueError\nExpected singleton: account.journal.afip_document_class(1, 2)')
2015-01-29 22:29:47,402 1226 INFO intest werkzeug: 192.168.0.102 - - [29/Jan/2015 22:29:47] "POST /web/dataset/call_kw/account.journal/write HTTP/1.1$
2015-01-29 22:30:28,740 1226 INFO intest werkzeug: 192.168.0.102 - - [29/Jan/2015 22:30:28] "POST /longpolling/poll HTTP/1.1" 200 -
2015-01-29 22:31:18,814 1226 INFO intest werkzeug: 192.168.0.102 - - [29/Jan/2015 22:31:18] "POST /longpolling/poll HTTP/1.1" 200 -
![error de validacion](https://cloud.githubusercontent.com/assets/8353194/5967666/457025e4-a7ee-11e4-9478-d0ce8e782ba2.png)

**Comment by noamix** [comment]
https://www.odoo.com/documentation/8.0/reference/orm.html

**Comment by noamix** [comment]
Es un error de la localizacion o seria un bug de odoo? saludos

**Comment by jjscarafia** [comment]
Era un bug en la localización. Solucionado
