### ISSUE TITLE
Error al intentar crear una nueva factura

### ISSUE THREAD

**Issue by leandrok** [ingadhoc/odoo-argentina#110]
> **Se produce un error al intentar crear una nueva factura**
> 
> _Version affectada:_
> - 8.0
> 
> _Pasos para reproducir:_
> 1. Ir al menu "Contabilidad" \ "Facturas de Cliente"
> 2. Oprimir el boton "Crear"
> 
> _Lo que pasa actualmente:_
> - Se produce el siguiente error:

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 5937, in onchange
    value = record[name]
  File "/opt/odoo/openerp/models.py", line 5640, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/openerp/fields.py", line 837, in **get**
    self.determine_draft_value(record)
  File "/opt/odoo/openerp/fields.py", line 945, in determine_draft_value
    self._compute_value(record)
  File "/opt/odoo/openerp/fields.py", line 884, in _compute_value
    self.compute(records)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 443, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/mnt/addons/odoo-argentina/l10n_ar_invoice/models/invoice.py", line 240, in _get_currency_values
    1.0, self.company_id.currency_id, round=False)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/res/res_currency.py", line 275, in compute
    assert self, "compute from unknown currency"
AssertionError: compute from unknown currency

> _Lo que debe pasar:_
> - Que no se produzca un error al intentar crear una nueva factura
> 
> _Analisis profunda:_
> - El mensaje de "unknown currency" es bastante claro, pero no entiendo por qué desconoce la moneda configurada. Estoy usando una unica compañia que tiene configurada la moneda pesos argentinos (ARS)
> - Esa moneda esta definida en res_currency. Hasta verifique que res_company.currency_id es igual a res_currency.id (# 20 en mi base). 
> - Solo necesito trabajar con pesos argentinos, no he configurado nada en otra moneda
> - Estoy trabajando con el commit mas reciente de la rama 8.0 (hice pull ayer nuevamente para ver si se corregia el problema)
>   - ¿Quizas me falta configurar algo o instalar algun modulo? Por las dudas instale el modulo l10n_ar_currency_update y configure Yahoo Finance para traer cotizaciones (por si el problema es que esta buscando una cotizacion etc) pero el problema persiste.
>   - Desde ya mil gracias por la ayuda que puedan darme! (esto es para mi primera instalacion en produccion que realice esta semana)

**Comment by jjscarafia** [comment]
Listo, ahora debería estar bien..
Gracias por reportar tan prolijo!

**Comment by leandrok** [comment]
Muchisimas gracias a vos Juan Jose por arreglar el problema tan rapido!

Un saludo grande,
Leandro
