### ISSUE TITLE
Luego de cancelar no puedo editar la factura utilizando el modulo mercadopago_payment

### ISSUE THREAD

**Issue by guzzi235** [ingadhoc/odoo-argentina#176]
Utilizando odoo 8 en ubuntu server 14 en produccion
luego de cancelar una factura electronica quiero modificar pero no me deja 
ingresar a la vista de la factura. desde ya gracias.

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3144, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3179, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3366, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/openerp/osv/fields.py", line 1460, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/addons/portal_sale/portal_sale.py", line 91, in <lambda>
    _payment_block_proxy = lambda self, *a, **kw: self._portal_payment_block(*a, **kw)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/portal_sale/portal_sale.py", line 104, in _portal_payment_block
    partner_id=this.partner_id.id, company_id=this.company_id.id, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/payment/models/payment_acquirer.py", line 300, in render_payment_block
    context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/payment/models/payment_acquirer.py", line 254, in render
    partner_values, tx_values = method(cr, uid, id, partner_values, tx_values, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/sources/extras/payment_mercadopago/models/mercadopago.py", line 83, in mercadopago_form_generate_values
    "title": "Orden Ecommerce " + tx_values["reference"],
TypeError: cannot concatenate 'str' and 'bool' objects

**Comment by jjscarafia** [comment]
Buenas, ya no estamos trabajando sobre v8 a menos que sean bugs de clientes. PR's bienvenidos igualmente
