### ISSUE TITLE
Couldn't load module l10n_ar_base_vat

### ISSUE THREAD

**Issue by martinfpas** [ingadhoc/odoo-argentina#21]
Buenas, estoy tratando de instalar la localizacion argentina pero no estoy pudiendo. Les copio los errores.

2015-03-12 19:15:01,221 9267 INFO demo openerp.modules.loading: loading 40 modules...
2015-03-12 19:15:01,222 9267 CRITICAL demo openerp.modules.module: Couldn't load module l10n_ar_base_vat
2015-03-12 19:15:01,222 9267 CRITICAL demo openerp.modules.module: 'string'
2015-03-12 19:15:01,222 9267 ERROR demo openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/l10n_ar_base_vat/**init**.py", line 22, in <module>
    import base_vat
  File "/usr/lib/python2.7/dist-packages/openerp/addons/l10n_ar_base_vat/base_vat.py", line 27, in <module>
    class res_partner(osv.osv):
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 254, in **init**
    setattr(self, name, column.to_field())
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 159, in to_field
    return Field.by_type[self._type](column=self, **self.to_field_args%28%29)
KeyError: 'string'

Ideas?

**Comment by jjscarafia** [comment]
La verdad es que no puedo replicar el error. Estás instalando el branch 8 de este repo sobre el 8 de odoo?

**Comment by martinfpas** [comment]
Sisi.

Raro, no? lo peor es que el error, en si, no me dice nada

**Comment by martinfpas** [comment]
Arme el entorno desde cero y salio andando.

Muchas gracias por su tiempo
