### ISSUE TITLE
Facturación electronica

### ISSUE THREAD

**Issue by martinfpas** [ingadhoc/odoo-argentina#22]
Estimados, estoy tratando de generar el certificado para poder probar la facturacion electronica, pero cuando presiono Generate en el "Issuer X509 Fields Name" me da el siguiente error:

Entorno: 
Servidor:  ubuntu 14
Aplicacion: odoo 8

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 939, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/crypto/wizard/generate_certificate.py", line 106, in on_generate
    certificate_obj.action_validate(cr, uid, active_ids)
AttributeError: 'crypto.certificate' object has no attribute 'action_validate'

Ideas??

**Comment by martinfpas** [comment]
agrego la consulta, 

el modulo crypto deberia ser este?? bzr branch lp:~moldeo-openerp-addons/openerp-crypto/8.0

**Comment by jjscarafia** [comment]
Nosotros usamos el que tenemos en ingadhoc/odoo-addons
Por el otro asunto la verdad es que no sé que decirte...
Saludos,
Juan

**Comment by jjscarafia** [comment]
no se depende más de crypto, cierro el issue porque estaría depreciado
