### ISSUE TITLE
problemas para instalar l10n_ar_afipws_fe

### ISSUE THREAD

**Issue by jobiols** [ingadhoc/odoo-argentina#34]
Hola,
Estoy siguiendo hace rato la localización de ustedes, y veo el tremendo trabajo que están haciendo, mis felicitaciones !!

Pero ahora tengo problemas para instalar el modulo l10n_ar_afipws_fe del repo 
adhoc/odoo-argentina branch 8.0.2
Estoy usando la imagen de docker adhoc/odoo-adhoc:8.0.3

Probé con una base limpia, y también con datos demo incluso creando la base con el repo 8.0.1 y luego pasando al 8.0.2 y haciendo update all, en cualquier caso me salta el siguiente error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 939, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/res/res_config.py", line 586, in execute
    action = self._install_modules(cr, uid, to_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/res/res_config.py", line 55, in _install_modules
    result = ir_module.button_immediate_install(cr, uid, to_install_ids, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 384, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 755, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 843, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 936, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 73, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 926, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: l10n_ar_invoice.view_argentinian_base_configuration" while parsing /mnt/extra-addons/odoo-argentina/l10n_ar_afipws/wizard/config_view.xml:5, near
<record id="view_argentinian_base_configuration" model="ir.ui.view">
            <field name="name">argentinian.base.settings</field>
            <field name="model">argentinian.base.config.settings</field>
            <field name="inherit_id" ref="l10n_ar_invoice.view_argentinian_base_configuration"/>
            <field name="arch" type="xml">
                <button name="%(account.action_account_journal_form)d" position="after">
                    <button string="Configure AFIP Certificates" icon="gtk-go-forward" name="%(act_afipws_certificate_alias)d" type="action" class="oe_link"/>
                </button>  
            </field>
        </record>

**Comment by jjscarafia** [comment]
mmm, si lo tenés actualizado es raro, ahora estamos usando el branch 8.0
como último branch, por diversos motivos tuvimos que volver atrás la idea
de usar los 8.0.1, 8.0.2 etc
Cuestión, te recomiendo el 8.0 y que pruebes actualizar l10n_ar_base
Saludos!

**Comment by jjscarafia** [comment]
Haría fañta actualizar l10n_ar_base
