### ISSUE TITLE
Error con la función afip_fce_es_anulacion

### ISSUE THREAD

**Issue by 3DOeste** [ingadhoc/odoo-argentina#351]
Tira error al querer validar o previsualizar una factura.

Odoo 12, ubuntu 18.04.

Se soluciona comentando la función.

**Comment by sotolucas** [comment]
Hola. Gracias por reportar el issue!
Podrías dar más información del error?

**Comment by 3DOeste** [comment]
Hola, copio el msj. que tira el servidor:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 757, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 737, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-267>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase/models/account_invoice.py", line 160, in create
    invoice = super(AccountInvoice, self).create(vals)
  File "<decorator-gen-262>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/multi-company/account_multic_fix/models/account_invoice.py", line 78, in create
    return super().create(vals)
  File "<decorator-gen-138>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_invoice.py", line 553, in create
    invoice = super(AccountInvoice, self.with_context(mail_create_nolog=True)).create(vals)
  File "<decorator-gen-111>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3563, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3663, in _create
    cr.execute(query, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "afip_fce_es_anulacion" of relation "account_invoice" does not exist
LINE 1: ...th_code", "afip_auth_code_due", "afip_auth_mode", "afip_fce_...

Puedo aportar alguna otra info?

**Comment by sotolucas** [comment]
Podrías darnos información sobre el tipo de documento que generaste y los pasos para reproducir el inconveniente?

**Comment by 3DOeste** [comment]
Estaba por validar una factura electrónica A, con el diario previamente configurado y el certificado de AFIP cargado correctamente. Luego de llenar todos los datos, toqué en previsualizar y saltó el error, lo mismo al tratar de validar. Si se comenta la función de anulación el problema se soluciona, aunque entiendo que no se podrían crear facturas de crédito si se necesitasen.

**Comment by sotolucas** [comment]
Hola! Podrías probar con actualizar el módulo con -u l10n_ar_afipws_fe o bien desde el menú Apps, entrando y luego clickeando actualizar?

**Comment by 3DOeste** [comment]
Hola, ahí lo actualicé. En principio al previsualizar una factura funciona OK, apenas tenga que facturar algo pruebo a ver si valida en afip. Muchas gracias!!!
