### ISSUE TITLE
Error al actualizar conceptos del padron AFIP

### ISSUE THREAD

**Issue by 3DOeste** [ingadhoc/odoo-argentina#363]
Odoo 12, Ubuntu server 18.04.

Al querer actualizar conceptos desde AFIP tira el sig. error, dentro de Facturacion-configuracion-Localizacion Argentina-Refrescar datos del padron de AFIP-conceptos

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-argentina/l10n_ar_account/wizard/res_config_settings.py", line 52, in refresh_concepts_from_padron
    self.refresh_from_padron("conceptos")
  File "/opt/odoo/odoo-argentina/l10n_ar_account/wizard/res_config_settings.py", line 77, in refresh_from_padron
    for line in data:
TypeError: 'bool' object is not iterable

**Comment by sotolucas** [comment]
Hola @3DOeste .
Muchas gracias por la info. Te tendremos al tanto.

**Comment by jjscarafia** [comment]
El error no se sigue replicando
