### ISSUE TITLE
[12.0] Error al cargar factura de proveedor

### ISSUE THREAD

**Issue by 3DOeste** [ingadhoc/odoo-argentina#368]
Dentro de facturación, en facturas del proveedor, al tratar de importar una factura tira el sig. error:

Odoo 12.0 Ubuntu 18.04
Mirando el error parece que necesita un n° de documento, pero no hay ningún campo para agregarlo.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_invoice_import_wizard.py", line 35, in create_invoices
    invoices += self._create_invoice_from_file(attachment)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_invoice_import_wizard.py", line 20, in _create_invoice_from_file
    invoice = invoice_form.save()
  File "/usr/lib/python3/dist-packages/odoo/tests/common.py", line 1401, in save
    values = self._values_to_save()
  File "/usr/lib/python3/dist-packages/odoo/tests/common.py", line 1427, in _values_to_save
    assert v is not False, "{} is a required field".format(f)
AssertionError: document_number is a required field

**Comment by 3DOeste** [comment]
La función necesita un formato factur-x (francia y alemania) para funcionar.
Cómo sugerencia, se podría eliminar el botón en la localización?

**Comment by jjscarafia** [comment]
Buenas @3DOeste . Gracias por reportar.
Lo ideal sería ver de implementar para que se importe de manera correcta.
Vamos a ver esto pero no tiene mucha prioridad para nosotros.
Si lo llegan a poder resolver de su lado, el PR es bienvenido.

Saludos!

**Comment by jjscarafia** [comment]
en la implementación v13/v14 debería estar resuelto
