### ISSUE TITLE
Error update l10n_ar_ux, openupgradelib dependence

### ISSUE THREAD

**Issue by martinllanos** [ingadhoc/odoo-argentina#479]
**Error update l10n_ar_ux, openupgradelib dependence**

*Version affectada:*

- 13.0e+ Revision: 01032021 

 *Pasos para reproducir:*
 
 1. Actualizar el submodulo del repositorio: git submodule update --remote --merge ingadhoc/odoo-argentina && git commit -a -m "[UPD] Update submodule ingadhoc/odoo-argentina"
  2. git push # Al server de odoo.sh
  3. Una vez que termina el build del branch staging, se ingresa al backend
  4. Se actualiza la lista de aplicaciones
  5. Se actualiza el modulo l10n_ar_ux
 
*Lo que pasa actualmente:*
 
  - Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-65>", line 2, in button_immediate_upgrade
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 634, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 419, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/odoo/modules/migration.py", line 171, in migrate_module
    mod = load_script(pyfile, name)
  File "/home/odoo/src/odoo/odoo/modules/migration.py", line 25, in load_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/odoo/src/user/ingadhoc/odoo-argentina/l10n_ar_ux/migrations/13.0.1.14.0/pre-migration.py", line 1, in <module>
    from openupgradelib import openupgrade
ModuleNotFoundError: No module named 'openupgradelib'
 
*Lo que debe pasar:*
 
  - Me tendria que actualizar normalmente a la ultima version del modulo.

 *Analisis profundo:*

  - Por consola de odoo.sh se instalo la libreria openupgradelib, pero no dio resultados positivos.
  - Sera que se tiene que agregar la libreria openupgradelib al requeriments.txt del repositorio https://github.com/ingadhoc/odoo-argentina ?

**Comment by jjscarafia** [comment]
Buenas! exacto, podrás hacer un PR agregando git+https://github.com/OCA/openupgradelib/@master
en el txt?

Gracias!

**Comment by jjscarafia** [comment]
cerrado en https://github.com/ingadhoc/odoo-argentina/pull/480
