### ISSUE TITLE
AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids'

### ISSUE THREAD

**Issue by ivanberthillood** [ingadhoc/odoo-argentina#507]
>Hola que tal tengo un error al sincronizar los numeros remotos con los locales no si todos tienen el mismo error.
>
>Al hacer click  * Sync Remote/Local Numbers* me da el siguiente error
> 
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo-custom-addons/l10n_ar_afipws_fe/models/journal.py", line 87, in sync_document_local_remote_number
    for journal_document_type in self.journal_document_type_ids:
AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids'

**Comment by jjscarafia** [comment]
Buenas!
Gracias por el reporte.
Me parece que ese error es de un modulo que no está en este repo.

Si estás usando el módulo l10n_ar_afipws_fe del repo https://github.com/ingadhoc/odoo-argentina-ce te pido que:
1. cargues el issue en dicho repo 
2. Antes verifiques si el error se replica en runbot (ver captura)
![image](https://user-images.githubusercontent.com/3016656/117566839-5783cf00-b08f-11eb-8501-1619f9b26a7c.png)
