### ISSUE TITLE
Error al imprimir informe Aeroo report para facturas no electrónicas

### ISSUE THREAD

**Issue by dbareiro** [ingadhoc/odoo-argentina#53]
Hola. Buenas tardes.

Estoy probando la localización de ADHOC evaluándola como alternativa para usar personalmente en producción. Les agradezco por el esfuerzo invertido y compartir este desarrollo con la comunidad.

Tomando como referencia la parte 1/2 del video publicado con nombre _Odoo v8 con localización Argentina a full en 10 minutos usando docker_, tuve el inconveniente que detallo a continuación.

Si hago la asociación del tipo de informe de Aeroo para que con las facturas de un punto de venta manual use el formato de informe manual, obtengo el siguiente error (el cual no se presenta en caso de no hacer esta asociación, usándose entonces el formato de informes correspondientes a facturas electrónicas con el espacio para el CAE):

```
Aeroo Reports: Error while generating the report.
Statement has no opening tag. </if>
Statement has no opening tag. </if>
For more reference inspect error logs.

<type 'exceptions.Exception'>,Aeroo Reports: Error while generating the report.
Statement has no opening tag. </if>
Statement has no opening tag. </if>
For more reference inspect error logs.,<traceback object at 0xb269611c>
```

Cuando se presenta esta excepción, revisando el log de Odoo encontré lo siguiente:

```
2015-08-31 14:27:33,918 402 INFO opcionlibre werkzeug: 10.1.0.40 - -
[31/Aug/2015 14:27:33] "POST /web/dataset/call_button HTTP/1.1" 200 -
2015-08-31 14:27:34,008 402 INFO opcionlibre report_aeroo: Start
process report.aeroo_report_ar_invoice (account.invoice)
None
2015-08-31 14:27:34,184 402 ERROR opcionlibre report_aeroo: Report
generation error!
Traceback (most recent call last):
  File "/opt/odoo/opcionlibre/addons/report_aeroo/report_aeroo.py",
line 539, in create_aeroo_report
    basic = Template(source=template_io, serializer=serializer,
lookup=DynamicLookup)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 239, in __init__
    encoding, lookup, allow_exec)
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.7-py2.7-linux-i686.egg/genshi/template/markup.py",
line 67, in __init__
    allow_exec=allow_exec)
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.7-py2.7-linux-i686.egg/genshi/template/base.py",
line 419, in __init__
    self._stream = self._parse(source, encoding)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 253, in _parse
    styles = template._parse(self.insert_directives(styles), encoding)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 303, in insert_directives
    self._handle_aeroo_tags(tree)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 422, in _handle_aeroo_tags
    r_statements, closing_tags = self._aeroo_statements(tree)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 401, in _aeroo_statements
    raise Exception("Statement has no opening tag. <%s>" % error_stm)
Exception: Statement has no opening tag. </if>
Traceback (most recent call last):
  File "/opt/odoo/opcionlibre/addons/report_aeroo/report_aeroo.py",
line 539, in create_aeroo_report
    basic = Template(source=template_io, serializer=serializer,
lookup=DynamicLookup)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 239, in __init__
    encoding, lookup, allow_exec)
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.7-py2.7-linux-i686.egg/genshi/template/markup.py",
line 67, in __init__
    allow_exec=allow_exec)
  File "/usr/local/lib/python2.7/dist-packages/Genshi-0.7-py2.7-linux-i686.egg/genshi/template/base.py",
line 419, in __init__
    self._stream = self._parse(source, encoding)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 253, in _parse
    styles = template._parse(self.insert_directives(styles), encoding)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 303, in insert_directives
    self._handle_aeroo_tags(tree)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 422, in _handle_aeroo_tags
    r_statements, closing_tags = self._aeroo_statements(tree)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py",
line 401, in _aeroo_statements
    raise Exception("Statement has no opening tag. <%s>" % error_stm)
Exception: Statement has no opening tag. </if>
2015-08-31 14:27:34,196 402 ERROR opcionlibre openerp.service.report:
Exception: ('Aeroo Reports: Error while generating the report.',
Exception('Statement has no opening tag. </if>',), 'Statement has no
opening tag. </if>', 'For more reference inspect error logs.')
Traceback (most recent call last):
  File "/opt/odoo/opcionlibre/openerp/service/report.py", line 93, in go
    result, format = openerp.report.render_report(cr, uid, ids,
object, datas, context)
  File "/opt/odoo/opcionlibre/openerp/report/__init__.py", line 40, in
render_report
    return registry['ir.actions.report.xml'].render_report(cr] uid,
ids, name, data, context)
  File "/opt/odoo/opcionlibre/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/opcionlibre/openerp/addons/base/ir/ir_actions.py",
line 155, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/opt/odoo/opcionlibre/addons/report_aeroo/report_aeroo.py",
line 866, in create
    res = fnct(cr, uid, ids, data, report_xml, context)
  File "/opt/odoo/opcionlibre/addons/report_aeroo/report_aeroo.py",
line 723, in create_source_pdf
    return self.create_single_pdf(cr, uid, ids, data, report_xml, context)
  File "/opt/odoo/opcionlibre/addons/report_aeroo/report_aeroo.py",
line 626, in create_single_pdf
    return self.create_aeroo_report(cr, uid, ids, data, report_xml,
context=context, output=output)
  File "/opt/odoo/opcionlibre/addons/report_aeroo/report_aeroo.py",
line 541, in create_aeroo_report
    self._raise_exception(e, print_id)
  File "/opt/odoo/opcionlibre/addons/report_aeroo/report_aeroo.py",
line 461, in _raise_exception
    raise Exception(_("Aeroo Reports: Error while generating the
report."), e, str(e), _("For more reference inspect error logs."))
Exception: ('Aeroo Reports: Error while generating the report.',
Exception('Statement has no opening tag. </if>',), 'Statement has no
opening tag. </if>', 'For more reference inspect error logs.')
2015-08-31 14:27:34,258 402 ERROR opcionlibre
openerp.addons.web.controllers.main: An exception occured during an
http request
Traceback (most recent call last):
  File "/opt/odoo/opcionlibre/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/opcionlibre/addons/web/controllers/main.py", line
1576, in index
    request.session.db, request.session.uid, request.session.password,
report_id)
  File "/opt/odoo/opcionlibre/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/opcionlibre/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/opcionlibre/openerp/service/report.py", line 34, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/opcionlibre/openerp/service/report.py", line 141, in
exp_report_get
    return _check_report(report_id)
  File "/opt/odoo/opcionlibre/openerp/service/report.py", line 119, in
_check_report
    raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: (u'Aeroo Reports: Error while generating the
report.\nStatement has no opening tag. </if>\nStatement has no opening
tag. </if>\nFor more reference inspect error logs.', (<type
'exceptions.Exception'>, Exception('Aeroo Reports: Error while
generating the report.', Exception('Statement has no opening tag.
</if>',), 'Statement has no opening tag. </if>', 'For more reference
inspect error logs.'), <traceback object at 0xae3c4a2c>))
2015-08-31 14:27:34,260 402 INFO opcionlibre werkzeug: 10.1.0.40 - -
[31/Aug/2015 14:27:34] "POST /web/report HTTP/1.1" 500 -
```

Si necesitan más información de mi entorno o alguna otra prueba adicional, por favor háganmelo saber. Las características del ambiente de pruebas son las siguientes:
- **Localización de ADHOC**: Branch 8.0.
- **Módulo Aeroo Reports**: Branch 8.0.
- **Módulo Aeroolib**: Master (la única disponible).
- **Informe que da el problema**: `Argentinian Aeroo Invoice` al asociar los documentos de factura y nota de crédito para un punto de venta de tipo "manual".

Muchas gracias.

Saludos,
Daniel

**Comment by jjscarafia** [comment]
Arreglado con https://github.com/ingadhoc/odoo-argentina/commit/cd286ac7421459c94bb34c3c563d028dcac34a43
Solo hace falta hacer un pull y debería andar.
Muchas gracias por reportarlo!

**Comment by dbareiro** [comment]
Genial! Que velocidad de respuesta!

Lo acabo de probar y funciona perfecto ahora.

Muchas gracias!

Saludos,
Daniel

**Comment by iscsolitario** [comment]
Buenas, me podrias decir que fue lo que se corrigió en el odt para que funcionara tengo el mismo problema en un reporte que genere y este solo es ocasional, no es en todas las impresiones.
De antemano gracias.

**Comment by jjscarafia** [comment]
@iscsolitario la verdad me mataste. No recuerdo. Parece ser un iterador o un if no cerrado en algún lugar. Lamentablemente no se puede ver el dif del odt.
Lamento no poder ayudar...

**Comment by MatiasBanega** [comment]
Hola buenas tardes, tengo un problema con aeroo report cuando imprimo en pdf cualquier informe me  los genera en blanco y hasta a veces me dice error del pdf.

La verdad que los queria felicitar por que la localizacion argentina de ADHOC para odoo version 11 esta muy bien diseñada.

gracias
