### ISSUE TITLE
Error al Generar una FCE Modulo - l10n_ar_ux 

### ISSUE THREAD

**Issue by adminwaves** [ingadhoc/odoo-argentina#664]
> **Error al Generar una FCE Modulo l10n_ar_ux *
>
> *Version afectada: v15*
> 
>  
> *Pasos para reproducir:*
> 
>  1. Se inicia el proceso de factura
>  2. Se elige el proveedor
>  3. Se selecciona 201 cod FCE
>  4. cuando se coloca CONFIRMAR muestra un error, 
>  5. Solo sucede con FCE
**>  **Detalle del error** 
res = super().wsfe_get_cae_request(client=client)
File "/home/odoo/src/enterprise/l10n_ar_edi/models/account_move.py", line 584, in wsfe_get_cae_request
invoice_number = self._l10n_ar_get_document_number_parts(
File "/home/odoo/src/user/ingadhoc1/odoo-argentina/l10n_ar_ux/models/account_move.py", line 99, in _l10n_ar_get_document_number_parts
elif "-" in document_number:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
raise exception.with_traceback(None) from new_cause
TypeError: argument of type 'bool' is not iterable**

> *Lo que pasa actualmente:*
> 
>  - Error Al crear una FCE ODoo V15
> 
> *Lo que debe pasar: Que la Factura de Crédito Electrónica Se emita con total normalidad*

**Comment by jjscarafia** [comment]
cerrado con https://github.com/ingadhoc/odoo-argentina/pull/667
