### ISSUE TITLE
Error Factura Electronica

### ISSUE THREAD

**Issue by adrianpaesani** [ingadhoc/odoo-argentina#87]
Hace varios días que no puedo conectarme para validar facturas, a continuación paso el error que me tira:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/adrian/utiles-odoo/adhoc/odoo-argentina/l10n_ar_afipws_fe/models/journal_afip_document_class.py", line 71, in action_get_pyafipws_last_invoice
    raise Warning(self.get_pyafipws_last_invoice()['msg'])
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/adrian/utiles-odoo/adhoc/odoo-argentina/l10n_ar_afipws_fe/models/journal_afip_document_class.py", line 84, in get_pyafipws_last_invoice
    ws = company.get_connection(afip_ws).connect()
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/adrian/utiles-odoo/adhoc/odoo-argentina/l10n_ar_afipws/models/res_company.py", line 130, in get_connection
    connection = self._create_connection(afip_ws, environment_type)
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/adrian/utiles-odoo/adhoc/odoo-argentina/l10n_ar_afipws/models/res_company.py", line 158, in _create_connection
    return self.connection_ids.create(auth_data)
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4230, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: integer out of range

La conexión con AFIP se realiza correctamente pero aparentemente es un error con el certificado, y estaba trabajando normalmente con dicho certificado.

**Comment by jjscarafia** [comment]
La verdad es que no nos está pasando, necesitaríamos más data para detectar
el porque...

**Comment by adrianpaesani** [comment]
Te subo parte del log, a ver si estos datos te sirven un poco más, porque la verdad es que no puedo encontrar la solución.

2015-11-02 21:54:54,571 1189 INFO gasol_01 openerp.addons.l10n_ar_afipws.models.res_company: Getting connection for company Gasol SRL and ws wsfe
2015-11-02 21:54:54,717 1189 INFO gasol_01 openerp.addons.l10n_ar_afipws.models.res_company: Running arg electronic invoice on production mode
2015-11-02 21:54:54,735 1189 INFO gasol_01 openerp.addons.l10n_ar_afipws.models.res_company: Creating connection for company Gasol SRL, environment type production and ws wsfe
2015-11-02 21:54:54,738 1189 INFO gasol_01 openerp.addons.l10n_ar_afipws.models.res_company: Using DB certificates
2015-11-02 21:54:54,760 1189 INFO gasol_01 openerp.addons.l10n_ar_afipws.models.res_company: Successful Connection to AFIP.
2015-11-02 21:54:54,762 1189 ERROR gasol_01 openerp.sql_db: bad query: INSERT INTO "afipws_connection" ("id", "afip_ws", "company_id", "sign", "token", "uniqueid", "expirationtime", "generationtime", "type", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('afipws_connection_id_seq'), 'wsfe', 1, 'm9EJpicYr1skNhWlL2j3M39oYfsbn+TFHXQaJOhVloTFgvSYMoi5K/oQWjZqDMGaLXe1vMJiT4SUPD/yFnusFL42zolzjiMBF4P+gl7nyRSd6rgO8jhGgJ5qdIQEeF1Qy1a9uTyrBMBgQA7TaVl5le1LGLMstyfwv7Fn5kDBVaU=', 'PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8c3NvIHZlcnNpb249IjIuMCI+CiAgICA8aWQgdW5pcXVlX2lkPSI0MjMzNzc0NTIxIiBzcmM9IkNOPXdzYWEsIE89QUZJUCwgQz1BUiwgU0VSSUFMTlVNQkVSPUNVSVQgMzM2OTM0NTAyMzkiIGdlbl90aW1lPSIxNDQ2NDkwNTI5IiBleHBfdGltZT0iMTQ0NjUzMzc4OSIgZHN0PSJDTj13c2ZlLCBPPUFGSVAsIEM9QVIiLz4KICAgIDxvcGVyYXRpb24gdmFsdWU9ImdyYW50ZWQiIHR5cGU9ImxvZ2luIj4KICAgICAgICA8bG9naW4gdWlkPSJDPWFyLCBTVD1zYWx0YSwgTD1zYWx0YSwgTz1nYXNvbCBzcmwsIE9VPWl0LCBTRVJJQUxOVU1CRVI9Q1VJVCAzMzcwODE4MzQyOSwgQ049ZmFjdHVyYW9kb28iIHNlcnZpY2U9IndzZmUiIHJlZ21ldGhvZD0iMjIiIGVudGl0eT0iMzM2OTM0NTAyMzkiIGF1dGhtZXRob2Q9ImNtcyI+CiAgICAgICAgICAgIDxyZWxhdGlvbnM+CiAgICAgICAgICAgICAgICA8cmVsYXRpb24gcmVsdHlwZT0iNCIga2V5PSIzMzcwODE4MzQyOSIvPgogICAgICAgICAgICA8L3JlbGF0aW9ucz4KICAgICAgICA8L2xvZ2luPgogICAgPC9vcGVyYXRpb24+Cjwvc3NvPgoK', 3201035444, '2015-11-03T03:56:29.026-03:00', '2015-11-02T15:56:29.026-03:00', 'production', 5, 5, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: integer out of range

2015-11-02 21:54:54,763 1189 ERROR gasol_01 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/adrian/utiles-odoo/adhoc/odoo-argentina/l10n_ar_afipws_fe/models/afip_point_of_sale.py", line 122, in action_get_connection
    self.company_id.get_connection(afip_ws).connect()
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/adrian/utiles-odoo/adhoc/odoo-argentina/l10n_ar_afipws/models/res_company.py", line 130, in get_connection
    connection = self._create_connection(afip_ws, environment_type)
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/adrian/utiles-odoo/adhoc/odoo-argentina/l10n_ar_afipws/models/res_company.py", line 158, in _create_connection
    return self.connection_ids.create(auth_data)
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4230, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: integer out of range

**Comment by adrianpaesani** [comment]
Juan, hice un git reset --hard HEAD^1 y no funcionó, pero después probé, git reset --hard HEAD^2 sobre odoo-argentina y funcionó la conexión. No estoy muy acostumbrado a git ya que lo uso poco, y más que nada para hacer las actualizaciones, pero por lo poco que me doy idea, me parece que el problema está en algunos de los commits que se hicieron en los rangos que volví hacia atrás (creo que está bien expresado). Espero no molestar. Muchas Gracias.

**Comment by jjscarafia** [comment]
Bueno, vamos a ver si lo podemos replicar...

**Comment by jjscarafia** [comment]
Listo, arreglado hoy! saludos
