### ISSUE TITLE
Problema al imprimir factura electrónica 

### ISSUE THREAD

**Issue by noamix** [ingadhoc/odoo-argentina#94]
Cuando mando a imprimir una factura electrónica me aparece este error, no se a que se puede deber

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 70, in wrap
    return f(_args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1593, in index
    file_name = reports.read(res_id[0], ['name'], context)['name']
  File "/opt/odoo/odoo-server/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/odoo-server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/report_aeroo/report_xml.py", line 458, in read
    res = super(report_xml, self).read(cr, user, ids, fields, context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3145, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/odoo-server/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3180, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo-server/openerp/api.py", line 254, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3312, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'ir.actions.report.xml'

**Comment by adrianpaesani** [comment]
Yo tuve el mismo problema en la última actualización de Odoo. Volvi a una versión anterior.

**Comment by jjscarafia** [comment]
Probé replicarlo hoy y no pude, actualicé odoo a la última versión y repo de odoo-argentina.
[Argentinian Aeroo Electronic Invoice (9).pdf](https://github.com/ingadhoc/odoo-argentina/files/66550/Argentinian.Aeroo.Electronic.Invoice.9.pdf)
